# SELECTION
SELECTION_TO_STR = "SELECTION_TO_STR"
SELECTION_TO_INT = "SELECTION_TO_INT"
SELECTION_FROM_LIST_LOW_LVL_OF_NULLS = "SELECTION_LOW_LVL_OF_NULLS"
SELECTION_FROM_LIST_MEDIUM_LVL_OF_NULLS= "SELECTION_MEDIUM_LVL_OF_NULLS"
SELECTION_FROM_LIST_HIGH_LVL_OF_NULLS= "SELECTION_HIGH_LVL_OF_NULLS"

# FILTERS
FILTRES = "FILTRES"

# SORT
SORT = "SORT"
SORT_DESC = "SORT_DESC"

# GROUP BY
GROUP_BY_SIMPLE_ATTRIBUTE = "GROUP_BY_SIMPLE_ATTRIBUTE"
GROUP_BY_ONE_ATTRIBUTE_FROM_LIST_SIMPLE = "GROUP_BY_ONE_ATTRIBUTE_FROM_LIST_SIMPLE"
GROUP_BY_TWO_ATTRIBUTES_FROM_LIST = "GROUP_BY_TWO_ATTRIBUTES_FROM_LIST"
GROUP_BY_ONE_ATTRIBUTE_FROM_LIST_COMPLEX = "GROUP_BY_ONE_ATTRIBUTE_FROM_LIST_COMPLEX"

# AGGREGATE FUNCTION
AGGREGATE_FUNCTION_SIMPLE_ATTRIBUTE = "AGGREGATE_FUNCTION_SIMPLE_ATTRIBUTE"
AGGREGATE_FUNCTION_ONE_FROM_LIST = "AGGREGATE_FUNCTION_ONE_FROM_LIST"
AGGREGATE_FUNCTION_TWO_FROM_LIST = "AGGREGATE_FUNCTION_TWO_FROM_LIST"
AGGREGATE_FUNCTION_ALL_ATTRIBUTES_FROM_LIST = "AGGREGATE_FUNCTION_ALL_ATTRIBUTES_FROM_LIST"

# CLOUD PAK
CONVERT_TYPE = "CONVERT_TYPE"
CONCATENATE_COLUMNS = "CONCATENATE_COLUMNS"
SPLIT_COLUMN = "SPLIT_COLUMN"
REPLACE_MISSING_VALUES = "REPLACE_MISSING_VALUES"
SELF_JOIN = "SELF_JOIN"
UNION_TABLES = "UNION_TABLES"
SAMPLE_TABLE = "SAMPLE_TABLE"
REMOVE_COLUMN = "REMOVE_COLUMN"
